name: Javascript

on:
    workflow_call:
    
jobs:
    call-analyse-workflow:
        name: Analyse Javascript code for SwagPaymentPayPalUnified
        uses: shopware5/docker-images-testing/.github/workflows/javascript-analysis.yml@main
        with:
            plugin-name: SwagPaymentPayPalUnified
